name: Automated API Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Apifox CLI
        run: npm install -g apifox-cli

      - name: Running Test Scenario
        run: apifox run --access-token afxp_c11b857dJWXVTeAIkjiQmSNMSTtlap3rNbQD -t 8621815 -e 48190079 -n 1 -r html,cli
